spring:
  application:
    name: simple-jpa
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: pirate